### ISSUE TITLE
请问如何配合前端做上传？

### ISSUE THREAD

**Issue by scott-leung** [huaweicloud/huaweicloud-sdk-nodejs-obs#1]
我们的ak、sk不可能直接暴露在浏览器层面的，所以有没有办法通过服务端nodejs来生成类似上传token（或者上传时签名由nodejs这边来提供）？没看到文档有相应的例子。

**Comment by JMD110** [comment]
可以通过设置桶策略实现, 文档地址https://support.huaweicloud.com/devg-obs/zh-cn_topic_0132788579.html

**Comment by JMD110** [comment]
> 可以通过设置桶策略实现, 文档地址https://support.huaweicloud.com/devg-obs/zh-cn_topic_0132788579.html
小程序中的一个示例
[微信小程序直传华为云OBS服务指南](https://bbs.huaweicloud.com/forum/thread-22457-1-1.html)
