### ISSUE TITLE
通过npm引入的时候，运行项目报错

### ISSUE THREAD

**Issue by ChangeXL** [huaweicloud/huaweicloud-sdk-nodejs-obs#10]
使用的Vue单页面引入
var ObsClient = require('esdk-obs-nodejs');
运行项目时报错
TypeError: Cannot read property 'match' of undefined

**Comment by wuchengqi577** [comment]
你好，根据你的描述不能定位出问题，可以提供一下出现错误的详细步骤嘛。
如果方便的话，麻烦提供一下demo

**Comment by NoAccident** [comment]
由于该问题1个月内未收到任何进一步反馈，因此暂时关闭问题，后续仍存在该问题请重新提issue咨询

**Comment by jinPeng90** [comment]
同样出现了这个问题

**Comment by jinPeng90** [comment]
> 你好，根据你的描述不能定位出问题，可以提供一下出现错误的详细步骤嘛。 如果方便的话，麻烦提供一下demo方便定位问题

执行 npm install esdk-obs-nodejs 后，node_modules文件中已经可以看到库了，在 vue页面中引用 var ObsClient = require('esdk-obs-nodejs'); 代码运行后，会报错 TypeError: Cannot read property 'match' of undefined
