### ISSUE TITLE
文件上传很慢

### ISSUE THREAD

**Issue by ooooevan** [huaweicloud/huaweicloud-sdk-nodejs-obs#11]
使用发现上传很慢，http很久才回来

![image](https://user-images.githubusercontent.com/25603236/126023263-ce7d89c0-53da-4a10-9510-321efaf20453.png)

**Comment by NoAccident** [comment]
您好，根据图中https请求返回共花费255ms是在正常的时间内呢。

**Comment by ooooevan** [comment]
一个文件200+ms，批量上传就特别久了
使用obsutil工具上传很快，这个这么慢，有什么不一样吗

**Comment by NoAccident** [comment]
文件多大呢？还有两种方式的代码提供一下。

**Comment by ooooevan** [comment]
到时换华为云服务器，走内网就不会慢
