### ISSUE TITLE
自定义 Meta 问题

### ISSUE THREAD

**Issue by Lionad-Morotar** [huaweicloud/huaweicloud-sdk-nodejs-obs#3]
通过 obs.setObjectMetadata 设置对象的自定义 data，能成功，但是最终会被服务器转换为小写名称，如下：

![image](https://user-images.githubusercontent.com/26913795/88940408-46b15c00-d2ba-11ea-83af-bd0816e5cd44.png)

我想要定义 'ContentType' 和 'ContentEncoding'，但是上传之后自动转为了 'contenttype' 和 'contentencoding'。额，有什么快速解决方案吗？

**Comment by Lionad-Morotar** [comment]
不过，尽管设置了对的元数据。OBS 返回文件时并没有携带我想要的 Content-Type。见下图，控制台显示我已经设置了正确的 Content-Type，第二张图显示了浏览器请求时，返回的错误的 Content-Type

![image](https://user-images.githubusercontent.com/26913795/88942934-79a91f00-d2bd-11ea-9aa6-db61b01c9351.png)

![TIM图片20200730233542](https://user-images.githubusercontent.com/26913795/88942891-6e55f380-d2bd-11ea-99aa-c2f9356e4c55.png)

**Comment by Lionad-Morotar** [comment]
如果手动在控制台设置对象的元数据，则不会出现该问题。

**Comment by JMD110** [comment]
示例: https://github.com/huaweicloud/huaweicloud-sdk-nodejs-obs/blob/master/examples/object-meta-sample.js

**Comment by JMD110** [comment]
ContentEncoding, ContentType是单独的参数,metaData是用户自定义的元数据参数
https://github.com/huaweicloud/huaweicloud-sdk-nodejs-obs/blob/9957cfd1c2111471489d20938690d66983c62c6f/lib/obsModel.js#L2572

**Comment by Lionad-Morotar** [comment]
> ContentEncoding, ContentType是单独的参数,metaData是用户自定义的元数据参数
> https://github.com/huaweicloud/huaweicloud-sdk-nodejs-obs/blob/9957cfd1c2111471489d20938690d66983c62c6f/lib/obsModel.js#L2572

Nice~ 晚上我试试
