### ISSUE TITLE
关于 vue

### ISSUE THREAD

**Issue by chen1749144759** [huaweicloud/huaweicloud-sdk-nodejs-obs#7]
请详细说明 nodejs依赖源以及依赖名称

**Comment by chen1749144759** [comment]
我没有在官网或者说明文档上看到npm依赖标识 或者 需要下载什么文件才能开始构建obsClient

**Comment by wuchengqi577** [comment]
您好，也许这个[文件](https://github.com/huaweicloud/huaweicloud-sdk-nodejs-obs/blob/master/package.json)可以帮助到您。

**Comment by NoAccident** [comment]
由于该问题1个月内未收到任何进一步反馈，因此暂时关闭问题，后续仍存在该问题请重新提issue咨询
