### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by dadalxx** [huaweicloud/huaweicloud-sdk-nodejs-obs#8]
通过客户端从OBS上下载/上传文件时，如果文件含有中文，则上传后或下载后的文件中则会出现乱码。

**Comment by wuchengqi577** [comment]
你好，根据你的描述不能定位出问题，可以提供一下出现错误的详细步骤嘛。
如果方便的话，麻烦提供一下demo方便定位问题。

**Comment by NoAccident** [comment]
由于该问题1个月内未收到任何进一步反馈，因此暂时关闭问题，后续仍存在该问题请重新提issue咨询
